import type { Metadata } from "next";
import "./globals.css";
import { fontRaleway, fontRighteous } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontRighteous.variable} ${fontRaleway.variable} ${fontRaleway.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
